import { Bell, Building2, Save, Shield } from "lucide-react";
import { useEffect, useState } from "react";
import { STORAGE_KEYS } from "../../../constants/storage";
import api from "../../../services/api";
import { readJson, writeJson } from "../../../utils/storage";
import OwnerPageShell from "../components/OwnerPageShell";
import { PageLoadingState } from "../../../components/LoadingSpinner";

type SettingsForm = { business_name: string; business_type: string; phone: string; address: string; notifications: { low_stock_alerts: boolean; daily_sales_summary: boolean; payment_updates: boolean; staff_activity: boolean } };
const initialForm: SettingsForm = { business_name: "", business_type: "", phone: "", address: "", notifications: { low_stock_alerts: true, daily_sales_summary: true, payment_updates: true, staff_activity: true } };
const notificationLabels = { low_stock_alerts: "Low stock alerts", daily_sales_summary: "Daily sales summary", payment_updates: "Payment status updates", staff_activity: "Staff account activity" };

function SettingsPage() {
  const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.get("/operations/settings").then((response) => { const { business, notifications } = response.data.data; setForm({ business_name: business.business_name || "", business_type: business.business_type || "", phone: business.phone || "", address: business.address || "", notifications: { low_stock_alerts: Boolean(notifications.low_stock_alerts), daily_sales_summary: Boolean(notifications.daily_sales_summary), payment_updates: Boolean(notifications.payment_updates), staff_activity: Boolean(notifications.staff_activity) } }); }).catch((requestError) => setError(requestError.response?.data?.message || "Unable to load settings.")).finally(() => setLoading(false)); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); try { setSaving(true); setError(""); setMessage(""); const response = await api.put("/operations/settings", form); const savedBusiness = response.data.data.business; const stored = readJson<Record<string, unknown>>(STORAGE_KEYS.business) || {}; writeJson(STORAGE_KEYS.business, { ...stored, ...savedBusiness }); setMessage("Business settings saved to the database."); } catch (requestError: any) { setError(requestError.response?.data?.message || "Unable to save settings."); } finally { setSaving(false); } }
  if (loading) return <PageLoadingState fullScreen label="Loading store settings..." />;
  return <OwnerPageShell badge={<><Shield size={14}/>Store settings</>} description="Configure the business details and alerts used across your TindaTrack workspace." title="Settings" topLabel="Workspace">
    {error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-600">{error}</div>}{message && <div className="mt-5 rounded-xl border border-leaf/20 bg-leaf/10 px-4 py-3 text-sm font-bold text-leaf-dark">{message}</div>}
    <form onSubmit={save} className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
      <div className="rounded-2xl border border-ink-line bg-white p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-leaf/10 text-leaf-dark"><Building2 size={19}/></span><div className="min-w-0"><h3 className="font-display text-lg font-bold text-pine sm:text-xl">Business information</h3><p className="text-xs font-bold text-ink-soft">Shown throughout the owner workspace.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs font-black uppercase tracking-wide text-ink-soft">Store name</span><input required value={form.business_name} onChange={(e) => setForm({ ...form, business_name: e.target.value })} className="h-11 w-full rounded-xl border border-ink-line px-4 text-sm font-semibold outline-none focus:border-leaf/50"/></label><label className="space-y-2"><span className="text-xs font-black uppercase tracking-wide text-ink-soft">Business type</span><input value={form.business_type} onChange={(e) => setForm({ ...form, business_type: e.target.value })} className="h-11 w-full rounded-xl border border-ink-line px-4 text-sm font-semibold outline-none focus:border-leaf/50" placeholder="Sari-sari store"/></label><label className="space-y-2"><span className="text-xs font-black uppercase tracking-wide text-ink-soft">Contact number</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="h-11 w-full rounded-xl border border-ink-line px-4 text-sm font-semibold outline-none focus:border-leaf/50"/></label><label className="space-y-2"><span className="text-xs font-black uppercase tracking-wide text-ink-soft">Store address</span><input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} className="h-11 w-full rounded-xl border border-ink-line px-4 text-sm font-semibold outline-none focus:border-leaf/50"/></label></div><button disabled={saving} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-leaf px-4 text-sm font-black text-white sm:w-auto"><Save size={17}/>{saving ? "Saving..." : "Save changes"}</button></div>
      <aside className="rounded-2xl border border-ink-line bg-paper p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-leaf/10 text-leaf-dark"><Bell size={19}/></span><div className="min-w-0"><h3 className="font-display text-lg font-bold text-pine sm:text-xl">Notifications</h3><p className="text-xs font-bold text-ink-soft">Store alert preferences</p></div></div><div className="mt-4 space-y-3">{(Object.keys(notificationLabels) as Array<keyof SettingsForm["notifications"]>).map((key) => <label key={key} className="flex items-center justify-between gap-3 rounded-xl border border-ink-line bg-white p-3 text-sm font-black text-ink"><span>{notificationLabels[key]}</span><input checked={form.notifications[key]} onChange={(e) => setForm({ ...form, notifications: { ...form.notifications, [key]: e.target.checked } })} className="h-5 w-5 shrink-0 accent-leaf" type="checkbox"/></label>)}</div></aside>
    </form>
  </OwnerPageShell>;
}
export default SettingsPage;
